version: "3.7"
services:
  session-plugin-dev:
    build:
      dockerfile: .devcontainer/Dockerfile
      context: .
    tty: true
    volumes:
      - ./:/src/:delegated
    container_name: session-plugin-dev
    environment:
      TZ: Asia/Tokyo
